const ALLOW_DAY = 'AVAILABILITY::ALLOW_DAY';
const BLOCK_DAY = 'AVAILABILITY::BLOCK_DAY';
const CHANGE_MONTH = 'AVAILABILITY::CHANGE_MONTH';
const START_SAVING = 'AVAILABILITY::START_SAVING';
const OPEN_EDIT_VIEW = 'AVAILABILITY::OPEN_EDIT_VIEW';
const CLOSE_EDIT_VIEW = 'AVAILABILITY::CLOSE_EDIT_VIEW';
const DATA_LOADED = 'AVAILABILITY::DATA_LOADED';

export {
  ALLOW_DAY,
  BLOCK_DAY,
  CHANGE_MONTH,
  START_SAVING,
  OPEN_EDIT_VIEW,
  CLOSE_EDIT_VIEW,
  DATA_LOADED,
};
