const ALLOW_DAY = 'AVAILABILITY::ALLOW_DAY';
const BLOCK_DAY = 'AVAILABILITY::BLOCK_DAY';
const CHANGE_MONTH = 'AVAILABILITY::CHANGE_MONTH';
const SAVE_CHANGES = 'AVAILABILITY::SAVE_CHANGES';
const OPEN_EDIT_VIEW = 'AVAILABILITY::OPEN_EDIT_VIEW';
const CLOSE_EDIT_VIEW = 'AVAILABILITY::CLOSE_EDIT_VIEW';
const DATA_LOADED = 'AVAILABILITY::DATA_LOADED';

export {
  ALLOW_DAY,
  BLOCK_DAY,
  CHANGE_MONTH,
  SAVE_CHANGES,
  OPEN_EDIT_VIEW,
  CLOSE_EDIT_VIEW,
  DATA_LOADED,
};
