// Search page
const CURRENT_PAGE_UPDATE = 'SEARCH::CURRENT_PAGE_UPDATE';

// System alerts
const FLASH_NOTIFICATION_ADD = 'FLASH::ADD_NOTIFICATION';
const FLASH_NOTIFICATION_REMOVE = 'FLASH::REMOVE_NOTIFICATION';

export {
  CURRENT_PAGE_UPDATE,
  FLASH_NOTIFICATION_ADD,
  FLASH_NOTIFICATION_REMOVE,
};
