require 'spec_helper'

describe PaypalService::DataTypes::IPN do

  # sample request params hashes

  order_created = {
    "txn_type"=> "express_checkout",
    "payment_date"=>"23:01:12 Sep 30, 2014 PDT",
    "last_name"=>"kjh",
    "receipt_id"=>"3609-0935-6989-4532",
    "residence_country"=>"GB",
    "pending_reason"=>"order",
    "item_name"=>"desc",
    "payment_gross"=>"",
    "mc_currency"=>"GBP",
    "verify_sign"=>"AWA3gWBJwNK7791rbM2f2XOEyzvbACNyf78ytgUBQNkB-vdmxBoY2Ait",
    "payer_status"=>"unverified",
    "test_ipn"=>"1",
    "tax"=>"0.00",
    "payer_email"=>"foobar@barfoo.com",
    "txn_id"=>"O-8VG2704956180171B",
    "quantity"=>"1",
    "receiver_email"=>"dev+paypal-user1@sharetribe.com",
    "first_name"=>"ljkh",
    "payer_id"=>"6M39X6RCYVUD6",
    "receiver_id"=>"URAPMR7WHFAWY",
    "item_number"=>"",
    "handling_amount"=>"0.00",
    "payment_status"=>"Pending",
    "shipping"=>"0.00",
    "mc_gross"=>"1.20",
    "custom"=>"",
    "transaction_entity"=>"order",
    "charset"=>"windows-1252",
    "notify_version"=>"3.8",
    "ipn_track_id"=>"d9520dcb18f6"
  }

  auth_created = {
    "mc_gross"=>"1.20",
    "auth_exp"=>"23:50:00 Oct 03, 2014 PDT",
    "protection_eligibility"=>"Ineligible",
    "payer_id"=>"6M39X6RCYVUD6",
    "tax"=>"0.00",
    "payment_date"=>"23:04:07 Sep 30, 2014 PDT",
    "payment_status"=>"Pending",
    "charset"=>"windows-1252",
    "first_name"=>"ljkh",
    "transaction_entity"=>"auth",
    "notify_version"=>"3.8",
    "custom"=>"",
    "payer_status"=>"unverified",
    "quantity"=>"1",
    "verify_sign"=>"A2S1fniRGsoquzRDbs4f5rc383f8A9BZtlhOnNThbBpkIOUsU.U6RJlP",
    "payer_email"=>"foobar@barfoo.com",
    "parent_txn_id"=>"O-8VG2704956180171B",
    "txn_id"=>"0L584749FU2628910",
    "payment_type"=>"instant",
    "remaining_settle"=>"10",
    "auth_id"=>"0L584749FU2628910",
    "last_name"=>"kjh",
    "receiver_email"=>"dev+paypal-user1@sharetribe.com",
    "auth_amount"=>"1.20",
    "receiver_id"=>"URAPMR7WHFAWY",
    "pending_reason"=>"authorization",
    "txn_type"=>"express_checkout",
    "item_name"=>"desc",
    "mc_currency"=>"GBP",
    "item_number"=>"",
    "residence_country"=>"GB",
    "test_ipn"=>"1",
    "receipt_id"=>"3609-0935-6989-4532",
    "handling_amount"=>"0.00",
    "transaction_subject"=>"",
    "payment_gross"=>"",
    "auth_status"=>"Pending",
    "shipping"=>"0.00",
    "ipn_track_id"=>"35b2bed5966"
  }

  payment_completed = {
    "mc_gross"=>"1.20",
    "auth_exp"=>"23:50:00 Oct 03, 2014 PDT",
    "protection_eligibility"=>"Ineligible",
    "payer_id"=>"6M39X6RCYVUD6",
    "tax"=>"0.00",
    "payment_date"=>"23:06:08 Sep 30, 2014 PDT",
    "payment_status"=>"Completed",
    "charset"=>"windows-1252",
    "first_name"=>"ljkh",
    "transaction_entity"=>"payment",
    "mc_fee"=>"0.24",
    "notify_version"=>"3.8",
    "custom"=>"",
    "payer_status"=>"unverified",
    "quantity"=>"1",
    "verify_sign"=>"AI36sk2Aln3iC.t.mla1wMizPRcQABXSTKSHu4uUNy3eGMDpl0JESlHN",
    "payer_email"=>"foobar@barfoo.com",
    "parent_txn_id"=>"0L584749FU2628910",
    "txn_id"=>"4BV77412CY217203L",
    "payment_type"=>"instant",
    "remaining_settle"=>"9",
    "auth_id"=>"0L584749FU2628910",
    "last_name"=>"kjh",
    "receiver_email"=>"dev+paypal-user1@sharetribe.com",
    "auth_amount"=>"1.20",
    "payment_fee"=>"",
    "receiver_id"=>"URAPMR7WHFAWY",
    "txn_type"=>"express_checkout",
    "item_name"=>"desc",
    "mc_currency"=>"GBP",
    "item_number"=>"",
    "residence_country"=>"GB",
    "test_ipn"=>"1",
    "receipt_id"=>"3609-0935-6989-4532",
    "handling_amount"=>"0.00",
    "transaction_subject"=>"",
    "payment_gross"=>"",
    "auth_status"=>"Completed",
    "shipping"=>"0.00",
    "ipn_track_id"=>"cf5793483cf91"
  }

  payment_refunded = {
    "mc_gross"=>"-1.20",
    "auth_exp"=>"23:50:00 Oct 03, 2014 PDT",
    "protection_eligibility"=>"Ineligible",
    "payer_id"=>"6M39X6RCYVUD6",
    "payment_date"=>"23:24:36 Sep 30, 2014 PDT",
    "payment_status"=>"Refunded",
    "charset"=>"windows-1252",
    "first_name"=>"ljkh",
    "transaction_entity"=>"payment",
    "mc_fee"=>"-0.04",
    "notify_version"=>"3.8",
    "reason_code"=>"refund",
    "custom"=>"",
    "verify_sign"=>"AGu.hbwMxRXoqDiyy-IJNOnULnvNAAs8Pg60O96MreRfhHhWgoCGDYFf",
    "payer_email"=>"foobar@barfoo.com",
    "parent_txn_id"=>"4BV77412CY217203L",
    "txn_id"=>"7HX881531H984174B",
    "payment_type"=>"instant",
    "remaining_settle"=>"9",
    "auth_id"=>"0L584749FU2628910",
    "last_name"=>"kjh",
    "receiver_email"=>"dev+paypal-user1@sharetribe.com",
    "payment_fee"=>"",
    "auth_amount"=>"1.20",
    "receiver_id"=>"URAPMR7WHFAWY",
    "item_name"=>"desc",
    "mc_currency"=>"GBP",
    "item_number"=>"",
    "residence_country"=>"GB",
    "test_ipn"=>"1",
    "receipt_id"=>"3609-0935-6989-4532",
    "handling_amount"=>"0.00",
    "transaction_subject"=>"",
    "payment_gross"=>"",
    "shipping"=>"0.00",
    "auth_status"=>"Completed",
    "ipn_track_id"=>"be492945b2622"
  }

  billing_agreement_cancelled = {
    "txn_type"=>"mp_cancel",
    "last_name"=>"Account",
    "mp_currency"=>"USD",
    "residence_country"=>"GB",
    "mp_status"=>"1",
    "mp_custom"=>"",
    "verify_sign"=>"ASVYRST0Jt3HL5ZvdLlfhfgxqvNbAjF-ZOgA2kiZUDAEcVV2IHG6RutL",
    "payer_status"=>"verified",
    "test_ipn"=>"1",
    "payer_email"=>"dev+paypal-user1@sharetribe.com",
    "first_name"=>"SandboxTest",
    "payer_id"=>"URAPMR7WHFAWY",
    "reason_code"=>"mp_2002",
    "payer_business_name"=>"SandboxTest Account's Test Store",
    "mp_id"=>"B-5WU95213TP0919018",
    "charset"=>"windows-1252",
    "notify_version"=>"3.8",
    "mp_desc"=>"commissions",
    "mp_cycle_start"=>"1",
    "ipn_track_id"=>"67e92d1e16ac5"
  }

  it "#from_params" do
    input_with_expected_type = [
      [payment_refunded, :payment_refunded],
      [order_created, :order_created],
      [auth_created, :authorization_created],
      [payment_completed, :payment_completed],
      [payment_refunded, :payment_refunded]
    ]

    input_with_expected_type.each do |(input, type)|
      expect(PaypalService::DataTypes::IPN.from_params(input)[:type]).to eq(type)
    end
  end

end
