const START_SAVING = 'LISTING_WORKING_HOURS::START_SAVING';
const CHANGES_SAVED = 'LISTING_WORKING_HOURS::CHANGES_SAVED';
const SAVING_FAILED = 'LISTING_WORKING_HOURS::SAVING_FAILED';
const OPEN_EDIT_VIEW = 'LISTING_WORKING_HOURS::OPEN_EDIT_VIEW';
const CLOSE_EDIT_VIEW = 'LISTING_WORKING_HOURS::CLOSE_EDIT_VIEW';
const DATA_LOADED = 'LISTING_WORKING_HOURS::DATA_LOADED';
const DATA_CHANGED = 'LISTING_WORKING_HOURS::DATA_CHANGED';

export {
  START_SAVING,
  CHANGES_SAVED,
  SAVING_FAILED,
  OPEN_EDIT_VIEW,
  CLOSE_EDIT_VIEW,
  DATA_LOADED,
  DATA_CHANGED,
};
