require File.expand_path('../rack_middleware/custom_cookie_renamer', __FILE__)
require File.expand_path('../rack_middleware/enforce_ssl', __FILE__)
require File.expand_path('../rack_middleware/health_check', __FILE__)
require File.expand_path('../rack_middleware/marketplace_lookup', __FILE__)
require File.expand_path('../rack_middleware/robots_generator', __FILE__)
require File.expand_path('../rack_middleware/session_context_middleware', __FILE__)
